### ISSUE TITLE
toggle light-dark dim; feature request

### ISSUE THREAD

**Issue by grossherr** [stephane-13/gnome-shell-extension-dim-background-windows#3]
this is just a suggestion/feature request/an idea to implement an option plus shortcut for a light and dark dim mode toggle

I've implemented it via one liner assigned to a shortcut which is changing the setting, but of course it also could be part of the feature set  

`bash -c "if [ $(dconf read /org/gnome/shell/extensions/dim-background-windows/brightness) == '0.75' ]; then dconf write /org/gnome/shell/extensions/dim-background-windows/brightness 0.1 && dconf write /org/gnome/shell/extensions/dim-background-windows/saturation 0.1; else dconf write /org/gnome/shell/extensions/dim-background-windows/brightness 0.75 && dconf write /org/gnome/shell/extensions/dim-background-windows/saturation 0.5; fi"`

**Comment by stephane-13** [comment]
The upcoming version will have a customizable global shortcut to quickly toggle the dimming effect on and off.
Would that be sufficient, or do you have a specific use case requiring multiple levels of brightness / saturation?

**Comment by grossherr** [comment]
I'm toggling two levels of brightness. I'm happy to do it via the one liner above. As I said, it's just a feature suggestion

**Comment by nekohayo** [comment]
If this could plug automatically into the global dark/light mode preference status, combined with the night theme switcher extension, this could allow dimming windows more significantly at night than during the day, which could be much easier on the eyes.

One usecase for this is, for instance, applications or websites that remain in light mode even when you are in dark mode, because they were not specifically designed with a dark mode variant in mind. This extension here could help reduce glare from such applications when they are not in active use, particularly on multiple monitors or on a projection screen.

**Comment by stephane-13** [comment]
That's a good idea indeed. I've been thinking about how to implement multiple levels of dimming, with the existing toggle key switching between them, but it quickly becomes difficult for the user to know what the current level is, especially if using like 4 or 5 levels or more.

So instead of doing that, I could add two extra dimming factors, one related to the dark / light mode and another one related to the night light mode.

Those factors would be applied on top of the existing brightness and saturation settings. It's probably easier than having to manage N different sets of brightness and saturation levels. I need to do some testing here.

**Comment by stephane-13** [comment]
Branch v11_gnome45 has new options to control the dimming effect in night light mode and when the dark style appearance is used. Will be submitted for review in the coming days.

I'm still checking if those changes can be backported to Gnome 42-44.

**Comment by stephane-13** [comment]
Branch v12 has been created with the same support for night light mode and dark style appearance for Gnome 42 to 44.

**Comment by stephane-13** [comment]
The latest version now supports different settings for the night light mode and dark style appearance (both being Gnome settings).

I'm tentatively closing this feature request. Although the extension now supports 3 levels of dimming - normal, night mode and dark style - the Gnome settings actually control which level is in use, not the global extension shortcut. So technically the original feature request is only partially addressed.

Having additional - i.e. secondary - dimming levels is not something easy to implement from the extension preferences point of view. It quickly becomes confusing for the user so set up, and the current dimming level is also not obvious. I'm not giving up adding those features, but it requires more thinking.
