### ISSUE TITLE
Add ability to only apply dim to the primary monitor or to exclude a particular monitor.Also add an option to control if the dimming effect applies to windows marked as always on top.

### ISSUE THREAD

**Issue by jcmolinajr** [stephane-13/gnome-shell-extension-dim-background-windows#6]
In my current setup I mainly use my secondary display to play media and thus can't currently make use of the extension.  Would it possible to add the ability to only apply dim to the primary monitor or to exclude a particular monitor?

**Comment by stephane-13** [comment]
It should be possible to differentiate the primary monitor from the other monitor(s) with the Window.is_on_primary_monitor() function. Just a guess, I didn't try that - and I have a single monitor :smile: 

However It might not be straightforward to target a specific monitor because the user wouldn't know which monitor has which id without trying each monitor id, which is cumbersome.

So one - probably easy - way to support such multi-monitors use case would be to add two options:
- a toggle to control the dimming effect on the primary monitor
- a toggle to control the dimming effect on the other (non-primary) monitor(s)

I will see if I can make that work.
