### ISSUE TITLE
gnome 45 support plox

### ISSUE THREAD

**Issue by egayghost** [stephane-13/gnome-shell-extension-dim-background-windows#8]

**Comment by stephane-13** [comment]
I don't have access to any operating system with gnome 45 at the moment, so I can't yet add support for it.
I'm planning to upgrade directly from Ubuntu 22.04 to 24.04 - which should have at least gnome 45 - as I like to stay on LTS versions.
I guess I could try with a virtual machine, but I'm not sure if that will work well because the extension is using a GLSL shader for the dimming effect.

**Comment by egayghost** [comment]
> I don't have access to any operating system with gnome 45 at the moment, so I can't yet add support for it. I'm planning to upgrade directly from Ubuntu 22.04 to 24.04 - which should have at least gnome 45 - as I like to stay on LTS versions. I guess I could try with a virtual machine, but I'm not sure if that will work well because the extension is using a GLSL shader for the dimming effect.

will wait till then, thank you

**Comment by stephane-13** [comment]
I don't have access to any operating system with gnome 45 at the moment, so I can't yet add support for it.
I'm planning to upgrade directly from Ubuntu 22.04 to 24.04 - which should have at least gnome 45 - as I like to stay on LTS versions.
I guess I could try with a virtual machine, but I'm not sure if that will work well because the extension is using a GLSL shader for the dimming effect.

**Comment by stephane-13** [comment]
Some good news: a virtual machine with Ubuntu 23.10 (using Gnome 45) is actually usable to test the extension, as the GLSL shader works as expected.

So I have created the new git branch [main_gnome45](https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/tree/main_gnome45) with the updated extension for Gnome 45.
I tested it in my VM, and it works fine.

Would you like to test that release on your computer before I submit it for review on extensions.gnome.org?
You can download the extension here: https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/blob/main_gnome45/dim-background-windows%40stephane-13.github.com.shell-extension.zip
Then you can install it with:
`gnome-extensions install dim-background-windows@stephane-13.github.com.shell-extension.zip`

**Comment by egayghost** [comment]
> Some good news: a virtual machine with Ubuntu 23.10 (using Gnome 45) is actually usable to test the extension, as the GLSL shader works as expected.
> 
> So I have created the new git branch [main_gnome45](https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/tree/main_gnome45) with the updated extension for Gnome 45. I tested it in my VM, and it works fine.
> 
> Would you like to test that release on your computer before I submit it for review on extensions.gnome.org? You can download the extension here: https://github.com/stephane-13/gnome-shell-extension-dim-background-windows/blob/main_gnome45/dim-background-windows%40stephane-13.github.com.shell-extension.zip Then you can install it with: `gnome-extensions install dim-background-windows@stephane-13.github.com.shell-extension.zip`

Hi, thanks for the test file and I can confirm it to you that it works well on my end too.

**Comment by stephane-13** [comment]
Thanks for the confirmation!
The new version with Gnome 45 support has just been approved on extensions.gnome.org, so I'm closing this issue.

**Comment by stephane-13** [comment]
Version 8 for Gnome 45 - technically identical to version 7 for Gnome 42-44 - has been approved here: https://extensions.gnome.org/review/47467
